import type { GalleryImage } from "./types";

export const galleryImages: GalleryImage[] = [
  {
    id: "canopy-geometry",
    slug: "canopy-geometry",
    title: "Canopy Geometry",
    category: "CANOPY / BOTANICAL",
    location: "Redwood National Park, CA",
    year: "2026",
    aspectRatio: "16 / 10",
    src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1600&auto=format&fit=crop",
    alt: "Morning sun rays piercing through towering redwood tree branches",
    caption:
      "Vertical perspective through primeval redwood canopy, capturing structural light patterns filtered through coastal fog.",
    cameraMeta: "35mm · ƒ/2.8 · 1/250s · ISO 100",
    featured: true,
  },
  {
    id: "alpine-ridge",
    slug: "alpine-ridge",
    title: "Alpine Ridge",
    category: "ALPINE / TERRAIN",
    location: "Dolomite Alps, Italy",
    year: "2026",
    aspectRatio: "3 / 2",
    src: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
    alt: "Rugged alpine limestone peaks shrouded in drifting morning clouds",
    caption:
      "Razor-sharp ridgelines rising through sea of low-hanging stratus clouds at sunrise.",
    cameraMeta: "70mm · ƒ/8.0 · 1/500s · ISO 200",
    featured: true,
  },
  {
    id: "botanical-matrix",
    slug: "botanical-matrix",
    title: "Botanical Matrix",
    category: "MACRO / TEXTURE",
    location: "Kew Botanical Gardens",
    year: "2026",
    aspectRatio: "4 / 3",
    src: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1600&auto=format&fit=crop",
    alt: "Macro photograph of Monstera leaf venation with condensation droplets",
    caption:
      "Cellular geometry and hydrostatic pressure evidenced through micro-venation pathways.",
    cameraMeta: "90mm Macro · ƒ/4.5 · 1/160s · ISO 160",
    featured: true,
  },
  {
    id: "glacial-runoff",
    slug: "glacial-runoff",
    title: "Glacial Runoff",
    category: "HYDROLOGY / BRAIDED",
    location: "Vatnajökull Outwash, Iceland",
    year: "2026",
    aspectRatio: "16 / 9",
    src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    alt: "Aerial patterns of volcanic glacial meltwater branching across black sand",
    caption:
      "Braided meltwater network carving sediment corridors across volcanic sand plains.",
    cameraMeta: "24mm · ƒ/5.6 · 1/1000s · ISO 100",
    featured: true,
  },
  {
    id: "dune-ribs",
    slug: "dune-ribs",
    title: "Dune Ribs",
    category: "GEOMORPHOLOGY / DESERT",
    location: "Sossusvlei, Namibia",
    year: "2026",
    aspectRatio: "2 / 1",
    src: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=1600&auto=format&fit=crop",
    alt: "Crest of a monumental red desert sand dune casting sharp black shadow",
    caption:
      "Wind-sculpted parabolic crest separating blinding light from deep ochre shadow.",
    cameraMeta: "50mm · ƒ/11 · 1/320s · ISO 100",
    featured: true,
  },
  {
    id: "nordic-reflection",
    slug: "nordic-reflection",
    title: "Nordic Reflection",
    category: "MIST / FJORD",
    location: "Geirangerfjord, Norway",
    year: "2026",
    aspectRatio: "4 / 3",
    src: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1600&auto=format&fit=crop",
    alt: "Mirror-like fjord reflecting evergreen slopes veiled in soft morning mist",
    caption:
      "Glassine surface water mirroring sheer glacial rock walls and silent spruce canopy.",
    cameraMeta: "35mm · ƒ/4.0 · 1/200s · ISO 125",
    featured: true,
  },
  {
    id: "fern-symmetry",
    slug: "fern-symmetry",
    title: "Fern Symmetry",
    category: "ORGANIC / SPIRAL",
    location: "Daintree Rainforest, Australia",
    year: "2026",
    aspectRatio: "1 / 1",
    src: "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1600&auto=format&fit=crop",
    alt: "Overhead view of radial tree fern fronds forming natural Fibonacci spiral",
    caption:
      "Centripetal unfolding of fiddlehead fronds exhibiting mathematical leaf distribution.",
    cameraMeta: "28mm · ƒ/3.5 · 1/125s · ISO 200",
    featured: true,
  },
  {
    id: "basalt-columns",
    slug: "basalt-columns",
    title: "Basalt Columns",
    category: "LITHIC / FRACTURE",
    location: "Reynisfjara, Iceland",
    year: "2026",
    aspectRatio: "3 / 2",
    src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop",
    alt: "Geometric columnar basalt cliffs rising from turbulent sea foam",
    caption:
      "Hexagonal jointing formed through contraction during rapid cooling of basaltic lava.",
    cameraMeta: "45mm · ƒ/6.3 · 1/400s · ISO 100",
    featured: true,
  },
  {
    id: "canyon-light",
    slug: "canyon-light",
    title: "Canyon Light",
    category: "EROSION / OPTICS",
    location: "Navajo Nation, Arizona",
    year: "2026",
    aspectRatio: "4 / 5",
    src: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=1600&auto=format&fit=crop",
    alt: "Sunbeam descending through twisting red sandstone slot canyon walls",
    caption:
      "Suspended dust grains catching collimated midday beam within water-carved slot chamber.",
    cameraMeta: "24mm · ƒ/8.0 · 1/60s · ISO 400",
    featured: true,
  },
  {
    id: "tundra-silence",
    slug: "tundra-silence",
    title: "Tundra Silence",
    category: "HORIZON / MINIMAL",
    location: "Lapland, Sweden",
    year: "2026",
    aspectRatio: "16 / 10",
    src: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?q=80&w=1600&auto=format&fit=crop",
    alt: "Monochrome misty horizon with solitary spruce standing above snowfield",
    caption:
      "Negative space and atmospheric extinction across subarctic taiga landscape.",
    cameraMeta: "85mm · ƒ/5.0 · 1/640s · ISO 100",
    featured: true,
  },
];
